FROM golang:1.13.3-stretch
RUN git clone https://github.com/cosmo0920/fluent-bit-go-s3.git
WORKDIR ./fluent-bit-go-s3
RUN go get -v -u \
	github.com/aws/aws-sdk-go/aws \
	github.com/aws/aws-sdk-go/aws \
	github.com/aws/aws-sdk-go/aws/credentials \
	github.com/aws/aws-sdk-go/aws/session \
	github.com/aws/aws-sdk-go/service/s3/s3manager \
	github.com/fluent/fluent-bit-go/output \
	github.com/json-iterator/go \
	github.com/stretchr/testify/assert
RUN make

FROM fluent/fluent-bit:1.3
COPY ./fluent_bit_custom.conf /fluent-bit/etc/fluent-bit.conf
COPY ./parser.conf /fluent-bit/etc/parser.conf
COPY ./stream_processor.conf /fluent-bit/etc/stream_processor.conf
COPY --from=0 /go/fluent-bit-go-s3/out_s3.so /fluent-bit/out_s3.so

CMD ["/fluent-bit/bin/fluent-bit", "-e", "/fluent-bit/out_s3.so", "-c", "/fluent-bit/etc/fluent-bit.conf"]